[package]
name = "ibag"
version = "0.3.5"
edition = "2021"
authors = ["Brian G"]
repository = "https://github.com/open1s/ibag.git"
description = "A thread-safe, immutable bag for holding any value"
license = "MIT"

[dependencies]
